language: c

os:
  - linux

sudo: required
distro: trusty

compiler:
  - gcc
  - clang

before_install:
  - sudo apt update
  - sudo apt install bison flex libmagic-dev zlib1g-dev

install:
  - HASMAGIC=1 WS_PARALLEL=1 WS_VERBOSEBUILD=1 make
